version: 2.1
jobs:
  build-client:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - client7-{{ checksum "client/package-lock.json" }}
      - run:
          name: npm install
          command: cd client ; npm install
      - run:
         name: build
         command: |
           cd client
           npm run build
      - save_cache:
          key: client7-{{ checksum "client/package-lock.json" }}
          paths:
            - client/node_modules/
      - persist_to_workspace:
          root: ~/
          paths:
            - project/client

  build-e2e:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - e2e-{{ checksum "e2e/package-lock.json" }}
      - run:
          name: npm install
          command: cd e2e ; npm install
      - save_cache:
          key: e2e-{{ checksum "e2e/package-lock.json" }}
          paths:
            - e2e/node_modules/
      - persist_to_workspace:
          root: ~/
          paths:
            - project/e2e
  eslint:
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
         at: ~/
      - run:
         name: eslint
         command: cd client && npm run lint --no-fix
  build-server:
    machine: true
    steps:
      - checkout
      - restore_cache:
         keys:
           - server3-{{ checksum "server/Pipfile.lock" }}-{{ checksum "server/Dockerfile" }}
      - run:
         name: Load Docker image layer cache
         command: test -f caches/server.tar && (docker load -i caches/server.tar) || echo 'Cache not found'
      - run:
         name: Build application Docker image
         command: docker build --tag server:latest -f server/Dockerfile .
      - run:
         name: flake8
         command: docker run -it server pipenv run flake8 --max-line-length=1000
      - run:
          name: Save built docker to workspace
          command: |
            mkdir -p ~/dockers
            docker save -o ~/dockers/server.tar server:latest
      - persist_to_workspace:
          root: ~/
          paths:
            - dockers
  cache-server:
    machine: true
    steps:
      - checkout
      - restore_cache:
         keys:
           - server3-{{ checksum "server/Pipfile.lock" }}-{{ checksum "server/Dockerfile" }}
      - run:
         name: Load Docker image layer cache
         command: test -f caches/server.tar && (docker load -i caches/server.tar) || echo 'Cache not found'
      - run:
         name: Save Docker image layer cache
         command: |
           mkdir -p caches/
           docker build --tag server -f server/Dockerfile .
           docker save $(docker history -q server | grep -v '^<missing>$') -o caches/server.tar
      - save_cache:
          key: server3-{{ checksum "server/Pipfile.lock" }}-{{ checksum "server/Dockerfile" }}
          paths:
            - caches/
  pytest:
    machine: true
    steps:
      - attach_workspace:
         at: ~/
      - run:
         name: Load Docker image layer cache
         command: docker load -i ~/dockers/server.tar
      - run:
         name: pytest
         command: docker run -it server pipenv run pytest
  build-docker:
    machine: true
    steps:
      - checkout
      - attach_workspace:
         at: ~/
      - run:
         name: Load Docker image layer cache
         command: docker load -i ~/dockers/server.tar
      - run: docker-compose build
      - run: docker-compose up --abort-on-container-exit --exit-code-from e2e
      - run:
          name: "Failure: output container logs to console"
          command: docker-compose logs
          when: on_fail
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            if [[ ${CIRCLE_BRANCH} == "master" ]]; then
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker build --tag $DOCKERHUB_USERNAME/elasticsearch-comrade .
              IMAGE_TAG=v$(python -c'print(__import__("json").load(open("client/package.json"))["version"])')
              docker push $DOCKERHUB_USERNAME/elasticsearch-comrade:latest
              if curl -s -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/repositories/$DOCKERHUB_USERNAME/elasticsearch-comrade/tags/$IMAGE_TAG/"| grep -q 404; then
                docker tag merged:latest $DOCKERHUB_USERNAME/elasticsearch-comrade:$IMAGE_TAG
                docker push $DOCKERHUB_USERNAME/elasticsearch-comrade:$IMAGE_TAG
              else
                echo Skipping version publish
              fi
            fi
workflows:
  build_and_test:
    jobs:
      - build-client
      - build-e2e
      - eslint:
          requires:
            - build-client
      - build-server
      - build-docker:
          requires:
            - build-server
            - build-client
            - build-e2e
      - cache-server
      - pytest:
          requires:
            - build-server
